title: Blog EIG2
email: 
description: >
   Some text !
url: "eig2.etalab.gouv.fr"
twitter_username: etalab

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


include:
   - _pages

exclude:
   - Gemfile
   - Gemfile.lock
   - deploy
   - circle.yml
