# Site settings
title: Entrepreneur d'Intérêt Général
email: steven.snoussi@data.gouv.fr
url: https://entrepreneur-interet-general.etalab.gouv.fr
description: "Entrepreneur d'Intérêt Général"
keywords: ""
meta_author: Etalab

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

color:
  primary: 25368C #80B3FF
  primary-rgb: "37,54,140" #"128,179,255"
  secondary: E10713 #FD6E8A
  secondary-dark: 233140 #A2122F

footer:
  social: Réseaux
  link: Liens Utiles
  credits: Crédits

social:
  - title: twitter
    url: http://twitter.com/etalab
  - title: github
    url: http://github.com/etalab

link:
  - title: CGU 
    url: /cgu.html
  - title: Règlement
    url: /reglement.html
  - title: Etalab
    url: https://etalab.gouv.fr
  - title: SGMAP
    url: http://modernisation.gouv.fr/

# Build settings
markdown: kramdown
permalink: pretty
